[package]
name = "grep-lite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
regex = "1"

[dev-dependencies]
duct = "0.13.6"
insta = "1.29.0"
tempfile = "3.5.0"
